//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightCom.MiP.Dispatcher.Plugin2Gis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightCom.MiP.Dispatcher.Plugin2Gis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить точку привязки....
        /// </summary>
        internal static string AddBindPointMenuItemName {
            get {
                return ResourceManager.GetString("AddBindPointMenuItemName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CheckedButton {
            get {
                object obj = ResourceManager.GetObject("CheckedButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CloseButton {
            get {
                object obj = ResourceManager.GetObject("CloseButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить все точки привязки?.
        /// </summary>
        internal static string DeleteAllBindPointsQuestion {
            get {
                return ResourceManager.GetString("DeleteAllBindPointsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить точку привязки?.
        /// </summary>
        internal static string DeleteBindPointQuestion {
            get {
                return ResourceManager.GetString("DeleteBindPointQuestion", resourceCulture);
            }
        }
        
        internal static byte[] eKey {
            get {
                object obj = ResourceManager.GetObject("eKey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста введите описание точки привязки..
        /// </summary>
        internal static string InvalidBindPointDescMessage {
            get {
                return ResourceManager.GetString("InvalidBindPointDescMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста введите корректное значение широты. Это дробное число, с точкой или запятой в качестве разделителя десятичных разрядов..
        /// </summary>
        internal static string InvalidBindPointLatMessage {
            get {
                return ResourceManager.GetString("InvalidBindPointLatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста введите корректное значение долготы. Это дробное число, с точкой или запятой в качестве разделителя десятичных разрядов..
        /// </summary>
        internal static string InvalidBindPointLongMessage {
            get {
                return ResourceManager.GetString("InvalidBindPointLongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МиП.
        /// </summary>
        internal static string MenuGroupName {
            get {
                return ResourceManager.GetString("MenuGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МиП.
        /// </summary>
        internal static string MenuSubMenuName {
            get {
                return ResourceManager.GetString("MenuSubMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOO ЛайтКом 2007.
        /// </summary>
        internal static string PluginCopyright {
            get {
                return ResourceManager.GetString("PluginCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модуль МиП предназначен для отображения на карте города мобильных объектов..
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon PluginIcon {
            get {
                object obj = ResourceManager.GetObject("PluginIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МиП.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PropertiesButton {
            get {
                object obj = ResourceManager.GetObject("PropertiesButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UncheckedButton {
            get {
                object obj = ResourceManager.GetObject("UncheckedButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
